#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d VIII IX X

bspc pointer -g focus

bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         false
bspc config click_to_focus                true

bspc config border_width        	  2
bspc config window_gap                    12

bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc rule -a google-chrome-stable desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell manage=off 
bspc rule -a Plasma manage=off
bspc rule -a plasma-desktop manage=off
bspc rule -a Screenkey manage=off

~/panel/panel &> /tmp/panel.log
